
// Auto-generated by openimis-config-vite.js
// Updated to use async/await for proper dynamic import handling
export const packages = [
  "@openimis/fe-core",
  "@openimis/fe-location",
  "@openimis/fe-medical",
  "@openimis/fe-medical_pricelist"
];

export async function loadModules(cfg = {}) {
  const loadedModules = [];

  // 🔄 Dynamically importing @openimis/fe-core
  try {
    const module = await import("@openimis/fe-core"); // ✅ CHANGED: use await instead of .then
    loadedModules.push(
      module.CoreModule(cfg["fe-core"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "@openimis/fe-core". Error: ${error}`);
    alert(`Failed to load module "@openimis/fe-core". See console for details.`);
  }

  // 🔄 Dynamically importing @openimis/fe-location
  try {
    const module = await import("@openimis/fe-location"); // ✅ CHANGED: use await instead of .then
    loadedModules.push(
      module.LocationModule(cfg["fe-location"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "@openimis/fe-location". Error: ${error}`);
    alert(`Failed to load module "@openimis/fe-location". See console for details.`);
  }

  // 🔄 Dynamically importing @openimis/fe-medical
  try {
    const module = await import("@openimis/fe-medical"); // ✅ CHANGED: use await instead of .then
    loadedModules.push(
      module.MedicalModule(cfg["fe-medical"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "@openimis/fe-medical". Error: ${error}`);
    alert(`Failed to load module "@openimis/fe-medical". See console for details.`);
  }

  // 🔄 Dynamically importing @openimis/fe-medical_pricelist
  try {
    const module = await import("@openimis/fe-medical_pricelist"); // ✅ CHANGED: use await instead of .then
    loadedModules.push(
      module.MedicalPriceListModule(cfg["fe-medical_pricelist"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "@openimis/fe-medical_pricelist". Error: ${error}`);
    alert(`Failed to load module "@openimis/fe-medical_pricelist". See console for details.`);
  }

  return loadedModules; // ✅ CHANGED: only return after all imports finish
}
