
// Auto-generated by openimis-config-vite.js
// Updated for Vite with local file dependencies
import { CoreModule } from "@openimis/fe-core";

export const packages = [
  "@openimis/fe-core",
  "@openimis/fe-home",
  "@openimis/fe-location",
  "@openimis/fe-insuree",
  "@openimis/fe-medical",
  "@openimis/fe-medical_pricelist",
  "@openimis/fe-product",
  "@openimis/fe-policy",
  "@openimis/fe-payer",
  "@openimis/fe-contribution",
  "@openimis/fe-payment",
  "@openimis/fe-claim",
  "@openimis/fe-tools",
  "@openimis/fe-calculation",
  "@openimis/fe-policyholder",
  "@openimis/fe-contribution_plan",
  "@openimis/fe-invoice",
  "@openimis/fe-language_fr"
];

export async function loadModules(cfg = {}) {
  const loadedModules = [];
  
  // 🔄 Statically imported CoreModule
  try {
    loadedModules.push(
      CoreModule(cfg["fe-core"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to initialize module "CoreModule". Error: ${error}`);
    alert(`Failed to load module "CoreModule". See console for details.`);
  }

  // 🔄 Dynamically importing HomeModule
  try {
    const module = await import("@openimis/fe-home");
    loadedModules.push(
      module.HomeModule(cfg["fe-home"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "HomeModule". Error: ${error}`);
    alert(`Failed to load module "HomeModule". See console for details.`);
  }

  // 🔄 Dynamically importing LocationModule
  try {
    const module = await import("@openimis/fe-location");
    loadedModules.push(
      module.LocationModule(cfg["fe-location"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "LocationModule". Error: ${error}`);
    alert(`Failed to load module "LocationModule". See console for details.`);
  }

  // 🔄 Dynamically importing InsureeModule
  try {
    const module = await import("@openimis/fe-insuree");
    loadedModules.push(
      module.InsureeModule(cfg["fe-insuree"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "InsureeModule". Error: ${error}`);
    alert(`Failed to load module "InsureeModule". See console for details.`);
  }

  // 🔄 Dynamically importing MedicalModule
  try {
    const module = await import("@openimis/fe-medical");
    loadedModules.push(
      module.MedicalModule(cfg["fe-medical"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "MedicalModule". Error: ${error}`);
    alert(`Failed to load module "MedicalModule". See console for details.`);
  }

  // 🔄 Dynamically importing MedicalPriceListModule
  try {
    const module = await import("@openimis/fe-medical_pricelist");
    loadedModules.push(
      module.MedicalPriceListModule(cfg["fe-medical_pricelist"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "MedicalPriceListModule". Error: ${error}`);
    alert(`Failed to load module "MedicalPriceListModule". See console for details.`);
  }

  // 🔄 Dynamically importing ProductModule
  try {
    const module = await import("@openimis/fe-product");
    loadedModules.push(
      module.ProductModule(cfg["fe-product"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "ProductModule". Error: ${error}`);
    alert(`Failed to load module "ProductModule". See console for details.`);
  }

  // 🔄 Dynamically importing PolicyModule
  try {
    const module = await import("@openimis/fe-policy");
    loadedModules.push(
      module.PolicyModule(cfg["fe-policy"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "PolicyModule". Error: ${error}`);
    alert(`Failed to load module "PolicyModule". See console for details.`);
  }

  // 🔄 Dynamically importing PayerModule
  try {
    const module = await import("@openimis/fe-payer");
    loadedModules.push(
      module.PayerModule(cfg["fe-payer"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "PayerModule". Error: ${error}`);
    alert(`Failed to load module "PayerModule". See console for details.`);
  }

  // 🔄 Dynamically importing ContributionModule
  try {
    const module = await import("@openimis/fe-contribution");
    loadedModules.push(
      module.ContributionModule(cfg["fe-contribution"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "ContributionModule". Error: ${error}`);
    alert(`Failed to load module "ContributionModule". See console for details.`);
  }

  // 🔄 Dynamically importing PaymentModule
  try {
    const module = await import("@openimis/fe-payment");
    loadedModules.push(
      module.PaymentModule(cfg["fe-payment"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "PaymentModule". Error: ${error}`);
    alert(`Failed to load module "PaymentModule". See console for details.`);
  }

  // 🔄 Dynamically importing ClaimModule
  try {
    const module = await import("@openimis/fe-claim");
    loadedModules.push(
      module.ClaimModule(cfg["fe-claim"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "ClaimModule". Error: ${error}`);
    alert(`Failed to load module "ClaimModule". See console for details.`);
  }

  // 🔄 Dynamically importing ToolsModule
  try {
    const module = await import("@openimis/fe-tools");
    loadedModules.push(
      module.ToolsModule(cfg["fe-tools"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "ToolsModule". Error: ${error}`);
    alert(`Failed to load module "ToolsModule". See console for details.`);
  }

  // 🔄 Dynamically importing CalculationModule
  try {
    const module = await import("@openimis/fe-calculation");
    loadedModules.push(
      module.CalculationModule(cfg["fe-calculation"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "CalculationModule". Error: ${error}`);
    alert(`Failed to load module "CalculationModule". See console for details.`);
  }

  // 🔄 Dynamically importing PolicyHolderModule
  try {
    const module = await import("@openimis/fe-policyholder");
    loadedModules.push(
      module.PolicyHolderModule(cfg["fe-policyholder"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "PolicyHolderModule". Error: ${error}`);
    alert(`Failed to load module "PolicyHolderModule". See console for details.`);
  }

  // 🔄 Dynamically importing ContributionPlanModule
  try {
    const module = await import("@openimis/fe-contribution_plan");
    loadedModules.push(
      module.ContributionPlanModule(cfg["fe-contribution_plan"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "ContributionPlanModule". Error: ${error}`);
    alert(`Failed to load module "ContributionPlanModule". See console for details.`);
  }

  // 🔄 Dynamically importing InvoiceModule
  try {
    const module = await import("@openimis/fe-invoice");
    loadedModules.push(
      module.InvoiceModule(cfg["fe-invoice"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "InvoiceModule". Error: ${error}`);
    alert(`Failed to load module "InvoiceModule". See console for details.`);
  }

  // 🔄 Dynamically importing LanguageFrModule
  try {
    const module = await import("@openimis/fe-language_fr");
    loadedModules.push(
      module.LanguageFrModule(cfg["fe-language_fr"] || {})
    );
  } catch (error) {
    console.error(`❌ Failed to import module "LanguageFrModule". Error: ${error}`);
    alert(`Failed to load module "LanguageFrModule". See console for details.`);
  }

  return loadedModules;
}
