name: Build

on:
  push:
      branches:
      - main
      - 'release/**'
      - develop
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Setup node v24
        with:
          node-version: "24"


      # Runs a single command using the runners shell
      - name: Prepare openIMIS Dependencies
        run: |
          npm install --include=dev
          node dev_tools/entrypoint-dev.js
          npm script/openimis-config-vite.js
      - name: Install dependencies
        run: npm install # Since we edit package.json with the openIMIS deps, we cannot use --frozen-lockfile

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-${GITHUB_REF_NAME_SLUG}-${{github.sha}}
          path: ./build/*

